version: '3'
services:
  # api-server:
  #   build: .
  #   tty: true
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - type: bind
  #       source: .
  #       target: /api-server
  #   depends_on:
  #     - db-server
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"