/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC165 } from "./ERC165";
export type { ERC1948 } from "./ERC1948";
export type { ERC721 } from "./ERC721";
export type { ERC721URIStorage } from "./ERC721URIStorage";
export type { IERC165 } from "./IERC165";
export type { IERC1948 } from "./IERC1948";
export type { IERC721 } from "./IERC721";
export type { IERC721Metadata } from "./IERC721Metadata";
export type { IERC721Receiver } from "./IERC721Receiver";
export type { MetaverseModel } from "./MetaverseModel";
